//Register
POST http://localhost:5005/admin/register
Content-Type: application/json

{
    "username" : "LTW Tech",
    "address" : "Milan, Italy",
    "authority" : {"role" : ["superadmin", "admin", "user"]},
    "phone_no" : "0123456789",
    "email" : "admin5@ltwtech.it",
    "password" : "1234",
    "avatar" : "/img/avatars/thumb-1.jpg"
}

###
//Login
POST http://localhost:5005/admin/login
Content-Type: application/json

{
    "email" : "admin@ltwtech.it",
    "password" : "1234",
    "signedIn" : false
}


###
//Get Admin
GET http://localhost:5005/admin/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBsdXh1cnljYXJzLml0IiwiaWF0IjoxNjYyMDkwMzIwLCJleHAiOjE2NjIwOTM5MjB9.eup5_EFQxifrWel7jQSMOjq6XYIT7c2iFVVyUbpxn0A


###
//Edit admin
PUT http://localhost:5005/admin/edit/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImVtYWlsIjoiYWRtaW5AbHV4dXJ5Y2Fycy5pdCIsImlhdCI6MTY2MDg5MDk5NiwiZXhwIjoxNjYwODk0NTk2fQ.JuURSeIhtk2JMcpeB8gdME_1gCiveOWxcsGxEuHd8YA
Content-Type: application/json

{
    "name" : "ALEX",
    "address" : "123, Main Rd, Mannar",
    "website" : "travelagent.com",
    "phone_no" : "5678901235",
    "vat_id" : "ASDFGHJKLP098",
    "profile" : "1660632804460-LTWDentalCare-HomeLayout.png"
}

###
PUT http://localhost:5005/admin/access_control/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImVtYWlsIjoiYWRtaW5AbHV4dXJ5Y2Fycy5pdCIsImlhdCI6MTY2MDg5MDk5NiwiZXhwIjoxNjYwODk0NTk2fQ.JuURSeIhtk2JMcpeB8gdME_1gCiveOWxcsGxEuHd8YA
Content-Type: application/json

{
    "is_deleted" : false
}

###
DELETE http://localhost:5005/admin/delete/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoiYWRtaW5AbHV4dXJ5Y2Fycy5pdCIsImlhdCI6MTY2MDkxODQyOSwiZXhwIjoxNjYwOTIyMDI5fQ.riMbldUorNmyieMkWsWLWNpwknAuJayPy8__gQ5voK8

###
POST http://localhost:5005/admin/forgot_password
Content-Type: application/json

{
    "email" : "vjvfc2k16@gmail.com"
}

###
POST http://localhost:5005/admin/reset_password/3/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZqdmZjMmsxNkBnbWFpbC5jb20iLCJpZCI6MywiaWF0IjoxNjcxMjk1MTE5LCJleHAiOjE2NzEyOTYwMTl9.v2elLrobRD-Ou0c_JCyhbB867-fKvp8fys4al-mzMes
Content-Type: application/json

{
    "password" : "12345"
}

###
PUT http://localhost:5005/admin/change_password/21
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsImF2YXRhciI6IjE2Njc1MzQ0OTg5MTEtZGVmYXVsdC1hdmF0YXIucG5nIiwidXNlcm5hbWUiOiJMVFcgVGVjaCIsImVtYWlsIjoiYWRtaW5AbHR3dGVjaC5pdCIsImF1dGhvcml0eSI6IntcInJvbGVcIjpbXCJhZG1pblwiLFwidXNlclwiXX0iLCJpYXQiOjE2Njc1NDA5NDAsImV4cCI6MTY2NzU0NDU0MH0.7WzgzSoqvWDm2SUvBsk0n_4qnRCtxiEzxoEtXdXOhcI
Content-Type: application/json

{
    "currentPassword" : "12345",
    "newPassword" : "1234"
}