###
#Get order by order id
POST http://localhost:5005/orders/create
Content-Type: application/json

{
    "restaurant_id": 1,
    "user_id" : 1,
    "products" : [
        {
            "product_id" : 3,
            "quantity" : 2,
            "addons" : [
                {
                    "addon_id" : 1,
                    "addon_name" : "cheese",
                    "unit_price" : 5,
                    "quantity" : 1
                }
            ] 
        },
        {
            "product_id" : 2,
            "quantity" : 1,
            "addons" : [
                {
                    "addon_id" : 2,
                    "addon_name" : "onion",
                    "unit_price" : 2,
                    "quantity" : 2
                },
                {
                    "addon_id" : 1,
                    "addon_name" : "cheese",
                    "unit_price" : 5,
                    "quantity" : 1
                }
            ] 
        }
    ],
    "order_date" : "08/12/2022",
    "order_time" : "10:00",
    "delivery_fee" : 25,
    "total_amount" : 124.00,
    "status" : "pending"
}

###
#Update status
PUT http://localhost:5005/orders/edit/5
Content-Type: application/json

{
    "status" : "processing"
}

###
#Get order by order id
GET http://localhost:5005/orders/5

###
#Get all orders by user id
GET http://localhost:5005/orders/all_orders/1

###
#Get all orders by restaurant id
GET http://localhost:5005/orders/all_restaurant_orders/13

###
#Get status by user id
GET http://localhost:5005/orders/get_status/5

###
#Delete order
DELETE http://localhost:5005/orders/delete/4