###
//Capture a charge
POST http://localhost:5005/payment/create_draft_invoice
Content-Type: application/json

{
    "admin_id": "6",
    "products_det": [{"product_id":"prod_MoqJQYl4h2Vvxe", "quantity": 3}],
    "quantity": 3,
    "currency": "eur"
}

###
//Direct payment
POST http://localhost:5005/payment/direct_payment
Content-Type: application/json

{
    "admin_id": "1",
    "amount": 20,
    "card_id": "cc-50-RZMph9e9EB",
    "currency": "eur",
    "receipt_email": "vjvfc2k16@gmail.com",
    "shipping_dets" : {
        "name" : "Alex",
        "phone" : "0123456789",
        "tracking_number" : "TR-123456",
        "address" : {
            "city" : "Milan",
            "country_code" : "IT",
            "line1" : "Test street",
            "line2" : "",
            "postal_code" : "20019",
            "state" : "Milano"
        }
    }
}

###
//Checkout session
POST http://localhost:5005/payment/checkout_session
Content-Type: application/json
